### PR TITLE
Added DockerFile for Pollers project with ffmpeg installation

### PR DESCRIPTION
**Pull request by ollleg**
Added an ffmpeg installation to the DockerFile for the CloudTranscoder project

### CODE REVIEW

**Comment by koxon** [comment]
Hello Ollleg! Thank you for this, this is great.

**Comment by koxon** [comment]
Ok. So several points here Ollleg.

CloudTranscode is just the Transcoding logic for CPE (CloudProcessingEngine), so technically you lunch the CPE daemon poller not Cloud Transcode directly.

So a Dockerfile shouldn't be in this directly but one level up in your CPE setup.

We already have a base Docker image with FFMpeg in it that you can find on Dockerhub: https://hub.docker.com/r/sportarc/cloudtranscode-base/
I guess I should add that to the documentation ... I will take a look.

What we do here at Sport Archive is we have a folder that contains a Dockerfile, the CPE-Poller directory and the CloudTranscode directory.

That Dockefile uses the base image, setup the two folders CPE and CT and start the Poller.

Here is that file:
```
FROM sportarc/cloudtranscode-base:latest
MAINTAINER Sport Archive, Inc.

RUN echo "date.timezone = UTC" >> /usr/local/etc/php/conf.d/timezone.ini
RUN apt-get update \
    && apt-get install -y zlib1g-dev autoconf \
    && docker-php-ext-install zip

COPY CloudProcessingEngine-Pollers/pollers /usr/src/cloudprocessingengine
WORKDIR /usr/src/cloudprocessingengine
RUN DEBIAN_FRONTEND=noninteractive TERM=screen \
    apt-get update \
    && apt-get install -y git \
    && make \
    && apt-get purge -y git \
    && apt-get autoremove -y

COPY CloudTranscode /usr/src/cloudtranscode
WORKDIR /usr/src/cloudtranscode
RUN DEBIAN_FRONTEND=noninteractive TERM=screen \
    apt-get update \
    && apt-get install -y git \
    && make \
    && apt-get purge -y git \
    && apt-get autoremove -y

COPY configs/* /etc/cloudtranscode/

ENTRYPOINT ["/usr/src/cloudprocessingengine/bootstrap.sh"]
```

**Comment by ollleg** [comment]
Hello Nicolas. Yes I have disabled these keys :) 
Thank you for this information. I'll try to use you docker image with ffmpeg installation

**Comment by sportarc** [comment]
I am updating the documentation to help with that

**Comment by koxon** [comment]
updated the documentation here: http://blog.bfansports.com/CloudProcessingEngine/start/local-stack.html

Thanks for the effort. Closing the PR.

**Pull request closed without merging**
